language: java
java:
  - 7.0 
  - 8.0
jdk:
  - oraclejdk7
  - oraclejdk8
notifications:
  email:
    recipients:
      - sepinaco@gmail.com
    on_success: never # default: change
    on_failure: always # default: always  